### ISSUE TITLE
demo link is not working gettting 500 Internal Server Error

### ISSUE THREAD

**Issue by marquez138** [rtCamp/wp-decoupled#18]

**Comment by elinlutz** [comment]
+ 1, would you please provide a demo again?

**Comment by wildrain** [comment]
Guys need to check the demo. I'm very interested about this project. Please fix the demo issue soon.

**Comment by imranhsayed** [comment]
Thank you for letting us know. We have updated the [demo link](https://wp-decoupled-imranhsayed.rtcamp.now.sh/)

Thank you
