### ISSUE TITLE
Single product pages don't work

### ISSUE THREAD

**Issue by w3bdesign** [rtCamp/wp-decoupled#24]
I am getting "An unexpected error has occurred."

Then if I try to refresh I get a "500 Internal Server Error."

Checking the browser console I see:

``` Error: "GraphQL error: Cannot query field "productBy" on type "RootQuery". Did you mean "product", "products", "productTag", "productType", or "postBy"?" ```

**Comment by achatainga** [comment]
I am having same issue atm

**Comment by achatainga** [comment]
For anyone encountering this Error: "GraphQL error: Cannot query field "productBy" on type "RootQuery". Did you mean "product", "products", "productTag", "productType", or "postBy"?"

I believe productId is deprecated so databaseid instead of delete it all together

**Comment by w3bdesign** [comment]
> 
> 
> For anyone encountering this Error: "GraphQL error: Cannot query field "productBy" on type "RootQuery". Did you mean "product", "products", "productTag", "productType", or "postBy"?"
> 
> I believe productId is deprecated so databaseid instead of delete it all together

@achatainga 

There has been some breaking changes to the WP Woo GraphQL plugin recently, where you have to specify the type of the ID you are using.

Feel free to take a look at my GraphQL queries in my repository where it is currently working:

https://github.com/w3bdesign/nextjs-woocommerce/blob/master/utils/gql/GQL_QUERIES.js
