### ISSUE TITLE
Can not run dev server

### ISSUE THREAD

**Issue by vann-at-cpcp-dot-tw** [rtCamp/wp-decoupled#25]
When I start the dev server, the terminal shows the following error message :

The static directory has been deprecated in favor of the public directory. https://err.sh/vercel/next.js/static-dir-deprecated
(node:95482) ExperimentalWarning: The fs.promises API is experimental
Defining routes from exportPathMap
Warning: Built-in CSS support is being disabled due to custom CSS configuration being detected.
See here for more info: https://err.sh/next.js/built-in-css-disabled

(node:95482) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined

**Comment by m-muhsin** [comment]
Hi @vann-at-cpcp-dot-tw,

The build is now passing. Next.js and other npm modules have been updated to the latest versions. The folder structure is also corrected accordingly.

Thanks for raising this issue!
