### ISSUE TITLE
Remove getInitialProps - Add IS(Re)G

### ISSUE THREAD

**Issue by imranhsayed** [rtCamp/wp-decoupled#36]
- [ ] Change the getInitialProps method to getStaticProps and getStaticPaths,  to take advantage of Next.js I[ncremental Static Regeneration (ISG).](https://nextjs.org/docs/basic-features/data-fetching#incremental-static-regeneration)

**Comment by m-muhsin** [comment]
Fixed in #39 

Thanks @NicestRudeGuy
