### ISSUE TITLE
Setup Cypress

### ISSUE THREAD

**Issue by imranhsayed** [rtCamp/wp-decoupled#62]
Setup Cypress
https://imranhsayed.medium.com/using-cypress-with-next-js-for-end-to-end-testing-cypress-nextjs-example-af100609cf16

**Comment by NicestRudeGuy** [comment]
Setup cyper and created basic spec 

![image](https://user-images.githubusercontent.com/9863419/105186272-8e24f080-5b57-11eb-99e2-f5334b291424.png)
